---
- name: check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  failed_when: "'' != cargo_exists.stdout"
  ignore_errors: true

- name: download rust installer
  become: true
  become_user: "{{ ansible_rust_host_user }}"
  when: cargo_exists is not failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: "u+rwx"
    owner: "{{ ansible_rust_host_user }}"
    force: true

- name: install rust/cargo
  become: true
  become_user: "{{ ansible_rust_host_user }}"
  when: cargo_exists is not failed
  shell: /tmp/sh.rustup.rs -y

- name: remove rust installer
  file:
    path: "/tmp/sh.rustup.rs"
    state: absent
  changed_when: false
