---
- name: check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: true
  changed_when: false

- name: uninstall cargo
  shell: rustup self uninstall -y
  when: cargo_exists.stdout != ''
  changed_when: false

- name: download rust installer
  become: true
  become_user: "{{ ansible_rust_host_user }}"
  changed_when: false
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: "u+rwx"
    owner: "{{ ansible_rust_host_user }}"
    force: true

- name: install rust/cargo
  changed_when: false
  become: true
  become_user: "{{ ansible_rust_host_user }}"
  shell: /tmp/sh.rustup.rs -y

- name: remove rust installer
  file:
    path: "/tmp/sh.rustup.rs"
    state: absent
  changed_when: false
